### ISSUE TITLE
2.  Navigation

### ISSUE THREAD

**Issue by katerynakim** [katerynakim/Semantic-layout-groupwebpage#2]
## 2.  Navigation

> assigned to `Ismail`  
> reviewed to `Razvan`

__As a site visitor, I want to read an introduction to this web page__

### Repository

- [x] developed on a branch called `nav`

### HTML

- [x] A navigattion element ...
- [x] ... with links on the pages of students
- [x] ... and class "nav"

### CSS

- [x] the "nav" class

---

**Comment by ismailtugan** [comment]
@katerynakim 
Kateryna can you assign me in this issue because I could not move or edit issue at the issue board

**Comment by katerynakim** [comment]
> @katerynakim 
> 
> Kateryna can you assign me in this issue because I could not move or edit issue at the issue board 

Done!@ismailtugan
Please accept also my invitation for collaboration of this project, because I cannot add you as a reviewer :)

**Comment by ismailtugan** [comment]
@katerynakim 
thank you  :+1:
